KnowledgeTestingSystem/Controllers/AnswersController.cs
using BLL.Interfaces;
using DAL.Models;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace KnowledgeTestingSystem.Controllers
{
    public class AnswersController : Controller
    {
        private readonly IAnswersService _answersService;

        public AnswersController(IAnswersService answersService)
        {
            _answersService = answersService;
        }

        // GET: Answer\Create
        public ActionResult Create(int questionId)
        {
            ViewData["id"] = questionId;
            return View(new Answer());
        }

        // POST: Answer\Create
        [HttpPost]
        public async Task<ActionResult> Create(Answer answer, int questionId)
        {
            try
            {
                await _answersService.CreateAsync(answer);
                return RedirectToAction("Details", "Questions", new { Id = questionId });
            }
            catch
            {
                return View(new Answer());
            }
        }

        // GET: Answer\Delete
        public async Task<ActionResult> Delete(int id, int questionId)
        {
            ViewData["id"] = questionId;
            return View(await _answersService.GetByIdAsync(id));
        }

        // POST: Answer\Delete
        [HttpPost]
        public async Task<ActionResult> Delete(int id, Answer answer, int questionId)
        {
            try
            {
                await _answersService.DeleteAsync(id);
                return RedirectToAction("Details", "Questions", new { Id = questionId });
            }
            catch
            {
                return View(new Answer());
            }
        }
    }
}

KnowledgeTestingSystem/Controllers/QuestionController.cs
using BLL.Interfaces;
using DAL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace KnowledgeTestingSystem.Controllers
{
    public class QuestionController : Controller
    {
        private readonly IQuestionsService _questionsService;

        public QuestionController(IQuestionsService questionsService)
        {
            _questionsService = questionsService;
        }

        // GET: Question\Create
        public ActionResult Create(int testId)
        {
            ViewData["id"] = testId;
            return View(new Question());
        }

        // POST: Question\Create
        [HttpPost]
        public async Task<ActionResult> Create(Question question, int testId)
        {
            try
            {
                question.TestId = testId;
                await _questionsService.CreateAsync(question);
                return RedirectToAction("Details", "Test", new { Id = testId });
            }
            catch
            {
                return View(new Question());
            }
        }

        // GET: Question\Details
        public async Task<ActionResult> Details(int id)
        {
            return View(await _questionsService.GetByIdAsync(id));
        }
    }
}

KnowledgeTestingSystem/Controllers/QuestionsController.cs
using BLL.Interfaces;
using DAL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace KnowledgeTestingSystem.Controllers
{
    public class QuestionsController : Controller
    {
        private readonly IQuestionsService _questionsService;

        public QuestionsController(IQuestionsService questionsService)
        {
            _questionsService = questionsService;
        }

        // GET: Question\Create
        public ActionResult Create(int testId)
        {
            ViewData["id"] = testId;
            return View(new Question());
        }

        // POST: Question\Create
        [HttpPost]
        public async Task<ActionResult> Create(Question question, int testId)
        {
            try
            {
                question.TestId = testId;
                await _questionsService.CreateAsync(question);
                return RedirectToAction("Details", "Tests", new { Id = testId });
            }
            catch
            {
                return View(new Question());
            }
        }

        // GET: Question\Details
        public async Task<ActionResult> Details(int id)
        {
            return View(await _questionsService.GetByIdAsync(id));
        }

        // GET: Question\Delete
        public async Task<ActionResult> Delete(int id, int testId)
        {
            ViewData["id"] = testId;
            return View(await _questionsService.GetByIdAsync(id));
        }

        // POST: Question\Delete
        [HttpPost]
        public async Task<ActionResult> Delete(int id, Question question, int testId)
        {
            try
            {
                await _questionsService.DeleteAsync(id);
                return RedirectToAction("Details", "Tests", new { Id = testId });
            }
            catch
            {
                return View(new Question());
            }
        }
    }
}

KnowledgeTestingSystem/Controllers/TestsController.cs
using BLL.Interfaces;
using DAL.Models;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace KnowledgeTestingSystem.Controllers
{
    public class TestsController : Controller
    {
        private readonly ITestsService _testsService;

        public TestsController(ITestsService testsService)
        {
            _testsService = testsService;
        }

        // GET: Test
        public async Task<ActionResult> Index()
        {
            return View(await _testsService.GetAllAsync());
        }

        // GET: Test/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View(new Test());
        }

        // POST: Test/Create
        [HttpPost]
        public async Task<ActionResult> Create(Test test)
        {
            try
            {
                await _testsService.CreateAsync(test);
                return RedirectToAction("Index", await _testsService.GetAllAsync());
            }
            catch
            {
                return View(new Test());
            }
        }

        // GET: Test/Details
        public async Task<ActionResult> Details(int id)
        {
            return View(await _testsService.GetByIdAsync(id));
        }
    }
}

KnowledgeTestingSystem/Views/Questions/Create.cshtml
@model DAL.Models.Question

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal card-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default p-0"  id=@ViewData["id"] /> |
                @Html.ActionLink("Back to List", "Details", "Tests", new { Id = ViewData["id"] }, new { @class = "btn btn-default p-0" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KnowledgeTestingSystem/Views/Questions/Delete.cshtml
@model DAL.Models.Question

@{
    ViewBag.Title = "Delete";
}

<h3 class="text-center">Are you sure you want to delete this?</h3>
<div>
    <dl class="dl-horizontal card-body">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color ps-3">
            <input type="submit" value="Delete" class="btn btn-primary btn-lg p-2 me-sm-3" id=@ViewData["id"]/>
            @Html.ActionLink("Back to List", "Details", "Tests", new { Id = @ViewData["id"] }, new { @class = "btn btn-outline-secondary btn-lg px-4" })
        </div>
    }
</div>

KnowledgeTestingSystem/Views/Questions/Details.cshtml
@model DAL.Models.Question

@{
    ViewBag.Title = "Details";
}

<div class="ps-0">
    <ul class="list-group">
        <li class="list-group-item active">@Html.DisplayFor(x => Model.Name)</li>
        @{ 
            foreach (DAL.Models.Answer item in Model.Answers)
            {
                <li class="list-group-item">
                    @Html.DisplayFor(x => item.Name)
                    @if (item.IsCorrect)
                    {
                        <span>
                            (Correct answer)
                        </span>
                    }
                    @Html.ActionLink("Delete answer", "Delete", "Answers", new { Id = item.Id, QuestionId = Model.Id }, new { @class = "btn btn-outline-secondary p-1" })
                </li>
            }
        }
    </ul>
    <div class="pt-4 ps-3">
        @Html.ActionLink("Create answer", "Create", "Answers", new { QuestionId = Model.Id, TestId = Model.TestId }, new { @class = "btn btn-primary btn-lg p-2 me-sm-3" })
        @Html.ActionLink("Back to list", "Details", "Tests", new { Id = Model.TestId }, new { @class = "btn btn-outline-secondary btn-lg px-4" })
    </div>
</div>